<{extends file="adminLayout.phtml"}>
<{block name="title" append}>
活动编辑
<{/block}>

<{block name="header-script"}>
<script>
    //var course=<{$courseList|default :[]}> ;
    var city_name='<{$school.school|default:'全国'}>';

</script>
<script type="text/javascript">
    $(document).ready(function() {
        $(".radioItem").change(function() {
            //var $course=<{$school.school|default :0}>;
            //alert($course);
            var $selectedvalue = $("input[name='priceType6']:checked").val();
            alert($selectedvalue);
            alert(city_name);
        });
    });
</script>
<{/block}>
<{block name="page-content" }>
<!-- page content -->
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>
                资源定价
            </h3>

        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>频道'<{$school.school}>'定价表 <!--<small>Sessions</small>--></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="#"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <!-- top tiles -->
                    <div class="row tile_count">
                        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
                            <div class="left"></div>
                            <div class="right">
                                <span class="count_top"><i class="fa fa-rmb"></i> <{$school.type}> <a data-toggle="modal" data-target=".bs-example-modal-sm" href=""><i class="fa fa-edit"></i></a></span>

                                <div class="count"><{$school.price}></div>
                            </div>

                        </div>
                        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
                            <div class="left"></div>
                            <div class="right">
                                <span class="count_top"><i class="fa fa-user"></i> 消费人次</span>
                                <div class="count green"><{$school.cusNumber}></div>
                            </div>
                        </div>
                        <div class="animated flipInY col-md-2 col-sm-4 col-xs-4 tile_stats_count">
                            <div class="left"></div>
                            <div class="right">
                                <span class="count_top"><i class="fa fa-book"></i> 课程数</span>
                                <div class="count"><{$school.courseNumber}></div>
                            </div>
                        </div>

                    </div>

                    <div class="well" style="overflow: auto">


                        <!-- 定价类型筛选 -->
                        <label class="control-label col-md-1">定价类型</label>
                        <div class="col-md-3">
                            <input type="checkbox" name="priceType[]" id="type1" value="credit" data-parsley-mincheck="2" required class="flat" checked="" /> 学分

                            <input type="checkbox" name="priceType[]" id="type2" value="coin" class="flat" checked="" /> U币

                            <input type="checkbox" name="priceType[]" id="type3" value="free" class="flat" checked=""/> 免费

                        </div>
                        <!-- 定价类型筛选-->

                        <!-- 是否定价筛选 -->
                        <label class="control-label col-md-1">是否定价</label>
                        <div class="col-md-3">
                            全部<input type="radio" class="flat" name="isPriced" id="pricedAll" value="all" checked="" required />
                            是<input type="radio" class="flat" name="isPriced" id="pricedYes" value="yes" />
                            否<input type="radio" class="flat" name="isPriced" id="pricedNo" value="no" />
                        </div>

                        <!-- 是否定价筛选-->

                        <br><br><br>

                        <!-- 课程名筛选 -->
                        <!--<div class="form-group">-->
                        <label class="control-label col-md-1 col-sm-1 col-xs-12">课程名</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" class="form-control" placeholder="输入课程名筛选">
                        </div>
                        <!--</div>-->
                        <!-- 课程筛选-->

                        <!-- 课程id筛选 -->
                        <!--<div class="form-group">-->
                        <label class="control-label col-md-1 col-sm-1 col-xs-12">课程id</label>
                        <div class="col-md-3 col-sm-3 col-xs-12">
                            <input type="text" class="form-control" placeholder="输入课程id筛选">
                        </div>
                        <!--</div>-->
                        <!-- 课程id筛选-->

                        <br><br><br>
                        <div class="ln_solid"></div>
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-primary">清空条件</button>
                            <button type="submit" class="btn btn-success">筛选课程</button>
                        </div>
                    </div>

                    <!-- 模态框-->
                    <div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
                        <div class="modal-dialog modal-sm">
                            <div class="modal-content">

                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                                    </button>
                                    <h4 class="modal-title" id="myModalLabel2">编辑频道定价</h4>
                                </div>
                                <form class="form-horizontal form-label-left" action="newSchoolPrice" method="get">
                                    <div class="modal-body">

                                        <div class="form-group">
                                            <label class="control-label col-md-3 col-sm-3 col-xs-12">定价类型</label>
                                            <div class="col-md-9 col-sm-9 col-xs-12">
                                                <{if $school.type == "U币"}>
                                                U币<input type="radio" class="flat" name="priceType" id="priceType" value=2  checked="checked"/>
                                                学分<input type="radio" class="flat" name="priceType" id="priceType" value=1 />
                                                免费<input type="radio" class="flat" name="priceType" id="priceType" value=3 />
                                                <{elseif $school.type == "学分"}>
                                                U币<input type="radio" class="flat" name="priceType" id="priceType" value=2  />
                                                学分<input type="radio" class="flat" name="priceType" id="priceType" value=1 checked="checked"/>
                                                免费<input type="radio" class="flat" name="priceType" id="priceType" value=3 />
                                                <{elseif $school.type == "免费"}>
                                                U币<input type="radio" class="flat" name="priceType" id="priceType" value=2  />
                                                学分<input type="radio" class="flat" name="priceType" id="priceType" value=1 />
                                                免费<input type="radio" class="flat" name="priceType" id="priceType" value=3 checked="checked"/>
                                                <{elseif $school.type == "未标价"}>
                                                U币<input type="radio" class="flat" name="priceType" id="priceType" value=2  />
                                                学分<input type="radio" class="flat" name="priceType" id="priceType" value=1 />
                                                免费<input type="radio" class="flat" name="priceType" id="priceType" value=3 />
                                                <{/if}>
                                            </div>
                                        </div>

                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">频道定价</label>
                                        <div class="col-md-9 col-sm-9 col-xs-12">
                                            选择折扣
                                            <select class="" name="discount">
                                                <option>1</option>
                                                <option>0.95</option>
                                                <option>0.9</option>
                                            </select>
                                        </div>

                                        <input type="text" name="id" value="<{$school.schoolId}>"  style="display:none;"/>

                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-primary" >提交</button>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                                    </div>
                                </form>
                            </div>

                        </div>
                    </div>
                    <!-- 模态框-->

                    <form class="form-horizontal form-label-left" action="newResourcePrice" method="get">
                    <!-- 表格-->
                    <table id="example" class="table table-striped responsive-utilities jambo_table">
                        <!--表头-->
                        <thead>
                        <tr class="headings">
                            <!--<th>
                                <input type="checkbox" class="tableflat">
                            </th>-->
                            <th>课程</th>
                            <th>章</th>
                            <th>节</th>
                            <th>定价类型</th>
                            <th>定价值</th>
                            <th>消费人次</th>
                        </tr>
                        </thead>
                        <!--表头-->
                        <tbody>

                        <{foreach item=course from=$courseList}>
                        <tr class="even pointer">
                            <!--<td class="a-center ">
                                <input type="checkbox" class="tableflat">
                            </td>-->

                            <td class=" "><{$course.course}></td>
                            <td class=" "><{$course.chapter}> </td>
                            <td class=" "><{$course.section}></td>
                            <td class=" ">
                                priceType<{$course.No}>
                                <{if $school.type=='免费'}>
                                免费<input type="radio" class="flat" name="priceType<{$course.No}>" id="priceFree<{$course.No}>" value="0<{$course.id}>" checked="yes"/></td>


                            <{elseif $course.type == '免费'}>
                                <{$school.type}><input type="radio" class="flat" name="priceType<{$course.No}>" id="priceNotFree<{$course.No}>" value="1<{$course.id}>" />
                                免费<input type="radio" class="flat" name="priceType<{$course.No}>" id="priceFree<{$course.No}>" value="0<{$course.id}>" checked="checked"/></td>
                            <{elseif $course.type != '免费'}>
                                <{$school.type}><input type="radio" class="flat" name="priceType<{$course.No}>" id="priceNotFree<{$course.No}>" value="1<{$course.id}>" checked="checked"/>
                                免费<input type="radio" class="flat" name="priceType<{$course.No}>" id="priceFree<{$course.No}>" value="0<{$course.id}>" /></td>
                            <{/if}>


                            <td class=" ">
                                <!-- 仅课程类型显示修改价格的输入框 -->
                                <{if $course.resourceType == 6 && $school.type=='免费'}>
                                <input type="text" id="price<{$course.No}>" name="price<{$course.No}>" required="required" data-parsley-id="5718" value = '<{$course.price}>' disabled="disabled" >
                                <{elseif $course.resourceType != 6}>
                                -
                                <{else}>
                                <input type="text" id="price<{$course.No}>" name="price<{$course.No}>" required="required" data-parsley-id="5718" value = <{$course.price}> >
                                <{/if}>
                            </td>
                            <td class=""><{$course.cusNumber}></td>
                        </tr>
                        <{/foreach}>

                        </tbody>
                    </table>
                    <!-- 表格-->
                    <input type="text" name="resourceNum" value="<{$resourceNum}>"  style="display:none;"/>
                    <input type="text" name="schoolId" value="<{$school.schoolId}>"  style="display:none;"/>
                    <div style = "position:fixed;bottom:0;left:250px;right:50px" class="x_panel"><button type="submit" class="btn btn-primary" >提交修改</button></div>
                    </form>
                </div>
            </div>
        </div>

        <br />
        <br />
        <br />


    </div>
</div>
<!--<script type="text/javascript">
    $(document).ready(function() {
        $(".flat").change(function() {
            alert(1);
            //var $selectedvalue = $("input[name='priceType6']:checked").val();
            //alert($selectedvalue);
        });
    });
</script>-->




<{/block}>

<{block name="footer-script"}>
<!-- 控制页面radio-->
<!--<script type="text/javascript" language="javascript">
    /*------判断radio是否有选中，获取选中的值--------*/
    $(function(){
            var val=$('input:radio[name="priceType1"]:checked').val();
            if(val==null){
                alert("什么也没选中!");
                return false;
            }
            else{
                alert(val);
            }
            var list= $('input:radio[name="list"]:checked').val();
            if(list==null){
                alert("请选中一个!");
                return false;
            }
            else{
                alert(list);
            }

    });
</script>-->

<!--<script type="text/javascript">
    $(document).ready(function() {
        $(".radioItem").change(function() {
            var $selectedvalue = $("input[name='priceType1']:checked").val();
             alert($selectedvalue);

        });
    });
</script>-->

<!-- 控制页面radio-->
<!-- Datatables -->
<script src="public/admin/js/datatables/js/jquery.dataTables.js"></script>
<script src="js/datatables/tools/js/dataTables.tableTools.js"></script>
<script>
    $(document).ready(function () {
        $('input.tableflat').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green'
        });
    });

    var asInitVals = new Array();
    $(document).ready(function () {
        var oTable = $('#example').dataTable({
            "oLanguage": {
                "sSearch": "Search all columns:"
            },
            "aoColumnDefs": [
                {
                    'bSortable': false,
                    'aTargets': [0]
                } //disables sorting for column one
            ],
            'iDisplayLength': 12,
            "sPaginationType": "full_numbers",
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "<?php echo base_url('assets2/js/Datatables/tools/swf/copy_csv_xls_pdf.swf'); ?>"
            }
        });
        $("tfoot input").keyup(function () {
            /* Filter on the column based on the index of this element's parent <th> */
            oTable.fnFilter(this.value, $("tfoot th").index($(this).parent()));
        });
        $("tfoot input").each(function (i) {
            asInitVals[i] = this.value;
        });
        $("tfoot input").focus(function () {
            if (this.className == "search_init") {
                this.className = "";
                this.value = "";
            }
        });
        $("tfoot input").blur(function (i) {
            if (this.value == "") {
                this.className = "search_init";
                this.value = asInitVals[$("tfoot input").index(this)];
            }
        });
    });
</script>

<!-- datepicker -->
<script type="text/javascript">
    $(document).ready(function () {

        var cb = function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
            $('#reportrange_right span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            //alert("Callback has fired: [" + start.format('MMMM D, YYYY') + " to " + end.format('MMMM D, YYYY') + ", label = " + label + "]");
        }

        var optionSet1 = {
            startDate: moment().subtract(29, 'days'),
            endDate: moment(),
            minDate: '01/01/2012',
            maxDate: '12/31/2015',
            dateLimit: {
                days: 60
            },
            showDropdowns: true,
            showWeekNumbers: true,
            timePicker: false,
            timePickerIncrement: 1,
            timePicker12Hour: true,
            ranges: {
                '今天': [moment(), moment()],
                '昨天': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                '过去7天': [moment().subtract(6, 'days'), moment()],
                '过去30天': [moment().subtract(29, 'days'), moment()],
                '本月': [moment().startOf('month'), moment().endOf('month')],
                '上月': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            opens: 'right',
            buttonClasses: ['btn btn-default'],
            applyClass: 'btn-small btn-primary',
            cancelClass: 'btn-small',
            format: 'MM/DD/YYYY',
            separator: ' to ',
            locale: {
                applyLabel: 'Submit',
                cancelLabel: 'Clear',
                fromLabel: 'From',
                toLabel: 'To',
                customRangeLabel: '常规',
                daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                firstDay: 1
            }
        };

        $('#reportrange_right span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));

        $('#reportrange_right').daterangepicker(optionSet1, cb);

        $('#reportrange_right').on('show.daterangepicker', function () {
            console.log("show event fired");
        });
        $('#reportrange_right').on('hide.daterangepicker', function () {
            console.log("hide event fired");
        });
        $('#reportrange_right').on('apply.daterangepicker', function (ev, picker) {
            console.log("apply event fired, start/end dates are " + picker.startDate.format('MMMM D, YYYY') + " to " + picker.endDate.format('MMMM D, YYYY'));
        });
        $('#reportrange_right').on('cancel.daterangepicker', function (ev, picker) {
            console.log("cancel event fired");
        });

        $('#options1').click(function () {
            $('#reportrange_right').data('daterangepicker').setOptions(optionSet1, cb);
        });

        $('#options2').click(function () {
            $('#reportrange_right').data('daterangepicker').setOptions(optionSet2, cb);
        });

        $('#destroy').click(function () {
            $('#reportrange_right').data('daterangepicker').remove();
        });

    });
</script>
<!-- datepicker -->
<script type="text/javascript">
    $(document).ready(function () {

        var cb = function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
            $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            //alert("Callback has fired: [" + start.format('MMMM D, YYYY') + " to " + end.format('MMMM D, YYYY') + ", label = " + label + "]");
        }

        var optionSet1 = {
            startDate: moment().subtract(29, 'days'),
            endDate: moment(),
            minDate: '01/01/2012',
            maxDate: '12/31/2015',
            dateLimit: {
                days: 60
            },
            showDropdowns: true,
            showWeekNumbers: true,
            timePicker: false,
            timePickerIncrement: 1,
            timePicker12Hour: true,
            ranges: {
                '今天': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            opens: 'left',
            buttonClasses: ['btn btn-default'],
            applyClass: 'btn-small btn-primary',
            cancelClass: 'btn-small',
            format: 'MM/DD/YYYY',
            separator: ' to ',
            locale: {
                applyLabel: 'Submit',
                cancelLabel: 'Clear',
                fromLabel: 'From',
                toLabel: 'To',
                customRangeLabel: 'Custom',
                daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                firstDay: 1
            }
        };
        $('#reportrange span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
        $('#reportrange').daterangepicker(optionSet1, cb);
        $('#reportrange').on('show.daterangepicker', function () {
            console.log("show event fired");
        });
        $('#reportrange').on('hide.daterangepicker', function () {
            console.log("hide event fired");
        });
        $('#reportrange').on('apply.daterangepicker', function (ev, picker) {
            console.log("apply event fired, start/end dates are " + picker.startDate.format('MMMM D, YYYY') + " to " + picker.endDate.format('MMMM D, YYYY'));
        });
        $('#reportrange').on('cancel.daterangepicker', function (ev, picker) {
            console.log("cancel event fired");
        });
        $('#options1').click(function () {
            $('#reportrange').data('daterangepicker').setOptions(optionSet1, cb);
        });
        $('#options2').click(function () {
            $('#reportrange').data('daterangepicker').setOptions(optionSet2, cb);
        });
        $('#destroy').click(function () {
            $('#reportrange').data('daterangepicker').remove();
        });
    });
</script>
<!-- /datepicker -->
<script type="text/javascript">
    $(document).ready(function () {
        $('#single_cal1').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_1"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
        $('#single_cal2').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_2"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
        $('#single_cal3').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_3"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
        $('#single_cal4').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_4"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#reservation').daterangepicker(null, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
    });
</script>
<!-- /datepicker -->
<{/block}>