<{extends file="layout.phtml"}> 
<{block name="title" append}>
修改密码
<{/block}>

 <{block name="header-css"}>

<link href="public/css/index.css" rel="stylesheet"/>
<link href="public/css/bootbox.css" rel="stylesheet"/>

<style>
    .error{
        color: #f00
    }
    .radio-inline label{
      font-weight: 100
    }
    a.btn-success {
    background-color: #5cb85c;
    border-color: #4cae4c;
    color: #fff;
}
</style>
 <{/block}>

 <{block name="page-content" }>

<div class="wrapper">
  <div class="row">
    <div class="col-lg-2">
      <div class="bordered">
        <ul class="nav nav-stacked ">
          <li > <a href="/user/setprofile"> 个人资料 <i class="glyphicon glyphicon-chevron-right"></i></a></li>
          <li><a href="/user/sethead"> 上传头像 <i class="glyphicon glyphicon-chevron-right"></i></a></li>
          <li  class="active"><a href="/user/resetpassword"> 修改密码 <i class="glyphicon glyphicon-chevron-right"></i></a></li>
          <li><a href="/user/resetmobile"> 手机验证 <i class="glyphicon glyphicon-chevron-right"></i></a></li>
        </ul>
      </div>
    </div>
    <div class="col-lg-10">
      <div class="main bordered">
        <h3 class="padding-left">修改密码</h3>
        <hr>
        <!--内容区开始-->
       <form role="form" class="form-horizontal" id="passwordForm" >
           <div class="form-group">
              <label class="col-sm-2 control-label no-padding-right" for="password_old">当前密码：</label>
              <div class="col-sm-10 ">
                <input type="password"  id="password_old" name='password_old' class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label no-padding-right" for="password_new">新密码：</label>
              <div class="col-sm-10 ">
                <input type="password"  id="password_new" name='password_new' class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label no-padding-right" for="confirmpassword_new">确认密码：</label>
              <div class="col-sm-10 ">
                <input type="password"  id="confirmpassword_new" name='confirmpassword_new' class="form-control">
              </div>
            </div>
            <hr>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <input class="btn btn-info" type="submit" value="保存修改"></input>
              </div>
            </div>
        </form>
        <!--内容区结束--> 
      </div>
    </div>
  </div>
</div>
<hr>
<{/block}>

<{block name="footer-script"}> 

   <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
   <script src="http://jqueryvalidation.org/files/dist/additional-methods.min.js"></script>
   <script src="public/js/bootbox.js"></script>
<script>


   $.fn.serializeObject = function() {
     var o = {};
     var a = this.serializeArray();
     $.each(a, function() {
       if (o[this.name]) {
         if (!o[this.name].push) {
           o[this.name] = [o[this.name]];
         }
         o[this.name].push(this.value || '');
       } else {
         o[this.name] = this.value || '';
       }
     });
     return o;
   };


   $("form").validate({
     submitHandler: function(form) {
       var formdata = $("form").serializeObject();
       $.post('/user/resetpassword', formdata, function(data) {


         if (parseInt(data.errno) < 0) {
           bootbox.info(data.error, function() {}, 3000);

         } else {
           bootbox.success('密码修改成功！下次登录记得用新密码哦！', function() {
           }, 3000);

         }

       })
     },
     rules: {
        password_old: {
         required: true,
         minlength: 6
       },
        password_new: {
         required: true,
         minlength: 6
       },
       confirmpassword_new: {
         required: true,
         equalTo: "#password_new"
       }
     },
     messages: {
       password_old: {
         required: '请输入密码！',
         minlength: '密码长度不够！'
       },
      password_new: {
         required: '请设置新密码！',
         minlength: '密码长度不够！'
       },
       password_again: {
         required: '请再次输入新密码！',

         equalTo: '两次密码输入不一致！'
       }
     }
   });




</script>
<{/block}>