<{extends file="adminLayout.phtml"}>
<{block name="title" append}>
活动编辑
<{/block}>
<{block name="page-content" }>
<!-- page content -->
<div class="">
    <div class="page-title">
        <div class="title_left">
            <h3>
                订单查询
            </h3>
        </div>

        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                                    <span class="input-group-btn">
                            <button class="btn btn-default" type="button">Go!</button>
                        </span>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="row">

        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <h2>用户订单 <!--<small>Sessions</small>--></h2>
                    <ul class="nav navbar-right panel_toolbox">
                        <li><a href="#"><i class="fa fa-chevron-up"></i></a>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Settings 1</a>
                                </li>
                                <li><a href="#">Settings 2</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="#"><i class="fa fa-close"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">


                    <div class="well" style="overflow: auto">
                        <form action = "getOrder" method = "get">

                        <!-- 列表日期筛选 -->
                        <label class="control-label col-md-1">选择日期</label>
                        <div class="col-md-4">

                            <fieldset>
                                <div class="control-group">
                                    <div class="controls">
                                        <div class="input-prepend input-group">
                                            <span class="add-on input-group-addon"><i class="glyphicon glyphicon-calendar fa fa-calendar"></i></span>
                                            <input type="text" style="width: 200px" name="date" id="reservation" class="form-control" value="<{$init.date}>" />
                                        </div>
                                    </div>
                                </div>
                            </fieldset>

                            <!--<div id="reportrange_right" class="pull-left" style="background: #fff; cursor: pointer; padding: 5px 10px; border: 1px solid #ccc">
                                <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
                                <span><input type="text" class="form-control" name = "date">December 30, 2014 - January 28, 2015</span> <b class="caret"></b>
                            </div>-->
                        </div>
                        <!--日期筛选-->



                        <br><br><br>

                        <!-- 订单状态筛选 -->
                        <label class="control-label col-md-1">订单状态</label>
                        <div class="col-md-3">
                            <select class="form-control" name = "status" id="status">
                                <option value = "-1">全部</option>
                                <{foreach item=sta from=$status}>
                                <{if $init.status == $sta.type}>
                                <option value = "<{$sta.type}>" selected = "selected"><{$sta.name}></option>
                                <{else}>
                                <option value = "<{$sta.type}>"><{$sta.name}></option>
                                <{/if}>
                                <{/foreach}>
                            </select>
                        </div>
                        <!-- 订单状态筛选-->

                        <!-- 订单类型筛选 -->
                        <label class="control-label col-md-1">订单类型</label>
                        <div class="col-md-3">
                            <select class="form-control" name = "payType">
                                <option value = "-1">全部</option>
                                <{foreach item=type from=$payType}>
                                <{if $init.payType == $type.type}>
                                <option value = "<{$type.type}>" selected = "selected"><{$type.name}></option>
                                <{else}>
                                <option value = "<{$type.type}>"><{$type.name}></option>
                                <{/if}>
                                <{/foreach}>
                            </select>
                        </div>
                        <!-- 订单类型筛选-->

                        <br><br><br>

                        <!-- 用户名筛选 -->
                        <!--<div class="form-group">-->
                            <label class="control-label col-md-1 col-sm-1 col-xs-12">用户名</label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" class="form-control" placeholder="输入用户名筛选" name = "mobile" value = "<{$init.mobile}>">
                            </div>
                        <!--</div>-->
                        <!-- 用户名筛选-->

                        <!-- 用户id筛选 -->
                        <!--<div class="form-group">-->
                            <label class="control-label col-md-1 col-sm-1 col-xs-12">用户id</label>
                            <div class="col-md-3 col-sm-3 col-xs-12">
                                <input type="text" class="form-control" placeholder="输入用户id筛选" name = "userId" value = "<{$init.userId}>">
                            </div>
                        <!--</div>-->
                        <!-- 用户id筛选-->

                        <br><br><br>
                        <div class="ln_solid"></div>
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                            <button type="reset" class="btn btn-primary">清空条件</button>
                            <button type="submit" class="btn btn-success">确认筛选</button>
                        </div>

                            </form>
                    </div>



                    <!-- 表格-->
                    共查询到<b><{$init.orderCount}></b>条订单数据，共<b><{$init.pageNumber}></b>页
                    <table id="example" class="table table-striped responsive-utilities jambo_table">
                        <!--表头-->
                        <thead>
                        <tr class="headings">
                            <!--<th>
                                <input type="checkbox" class="tableflat">
                            </th>-->
                            <th>订单id</th>
                            <th>下单时间</th>
                            <th>用户id</th>
                            <th>用户名</th>
                            <th>类型</th>
                            <th>订单状态</th>
                            <th>数值</th>
                            <th>充值id</th>
                            <th class=" no-link last"><span class="nobr">资源内容</span>
                            </th>
                        </tr>
                        </thead>
                        <!--表头-->
                        <tbody>
                        <{$index=0}>
                        <{foreach item=order from=$orderList}>
                        <tr class="even pointer">
                            <!--<td class="a-center ">
                                <input type="checkbox" class="tableflat">
                            </td>-->
                            <td class=" "><{$order.id}></td>
                            <td class=" "><{$order.createTime}> </td>
                            <td class=" "><{$order.userId}>
                            </td>
                            <td class=" "><{$order.mobile}></td>
                            <td class=" "><{$order.payType}></td>
                            <td class="a-right a-right "><{$order.status}></td>
                            <td class = ""><{$order.amount}></td>
                            <td class = ""><{$order.coinId}></td>
                            <td>
                                <{if $order.resource}>
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-sm-<{$order.no}>">查看购买资源</button>
                                <!-- 模块框-->
                                <div class="modal fade bs-example-modal-sm-<{$order.no}>" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-sm">
                                        <div class="modal-content">

                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span>
                                                </button>
                                                <h4 class="modal-title" id="myModalLabel2">该用户购买了</h4>
                                            </div>
                                            <div class="modal-body">
                                                <h4><{$order.schoolName}>-<{$order.schoolTitle}>下的<{$order.courseCount}>门课程</h4>
                                                <{foreach item=res from=$order.resource}>
                                                <p><{$res.resourceName}></p>
                                                <{/foreach}>
                                                <!--<{$order.resource}>-->
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-primary" data-dismiss="modal">关闭</button>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <!-- 模态框-->
                                <{else}>
                                <button type="button" class="btn btn-default btn-primary" disabled="disabled">查看购买资源</button>
                                <{/if}>
                            </td>
                            </td>

                        </tr>
                        <{/foreach}>
                        <!-- Small modal -->
                        </tbody>

                    </table>
                    <!-- 表格-->

                    <!-- 分页-->
                    <nav style="float:right">
                        <ul class="pagination" >
                            <{if $init.page==1}>
                            <li class="disabled">
                                <{else}>
                            <li>
                                <{/if}>
                                <a href="getOrder?page=<{$init.page-1}>&date=<{$init.date}>&status=<{$init.status}>&payType=<{$init.payType}>&userId=<{$init.userId}>&mobile=<{$init.mobile}>" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>

                            <{foreach item=page from=$pagination}>
                            <{if $init.page==$page}>
                            <li id="page<{$page}>" class="active">
                                <{else}>
                            <li id="page<{$page}>">
                                <{/if}>
                                <a href="getOrder?page=<{$page}>&date=<{$init.date}>&status=<{$init.status}>&payType=<{$init.payType}>&userId=<{$init.userId}>&mobile=<{$init.mobile}>">
                                    <{$page}></a></li>
                            <{/foreach}>
                            <{if $init.page==$init.pageNumber}>
                            <li class="disabled">
                                <{else}>
                            <li>
                                <{/if}>
                                <a href="getOrder?page=<{$init.page+1}>&date=<{$init.date}>&status=<{$init.status}>&payType=<{$init.payType}>&userId=<{$init.userId}>&mobile=<{$init.mobile}>" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <!-- 分页-->

                </div>
            </div>
        </div>

        <br />
        <br />
        <br />

    </div>
</div>
<{/block}>

<{block name="footer-script"}>

<!-- Datatables -->
<script src="public/admin/js/datatables/js/jquery.dataTables.js"></script>
<script src="js/datatables/tools/js/dataTables.tableTools.js"></script>
<!--<script>
    $('#page1').click(function(){
        alert("Text: " + $("#status").val());
        $('#page1').innerHTML = ""
    });
</script>-->
<script>
    $(document).ready(function () {
        $('input.tableflat').iCheck({
            checkboxClass: 'icheckbox_flat-green',
            radioClass: 'iradio_flat-green'
        });
    });

    //var asInitVals = new Array();
    /*$(document).ready(function () {
        var oTable = $('#example').dataTable({
            "aoColumnDefs": [
                {
                    'bSortable': false,
                    'aTargets': [0]
                } //disables sorting for column one
            ]
            //'iDisplayLength': 12,
            //"sPaginationType": "full_numbers",
            //"dom": 'T<"clear">lfrtip',
        });
    });*/
</script>

<!-- datepicker -->
<script type="text/javascript">
    $(document).ready(function () {

        var cb = function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
            $('#reportrange_right span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            //alert("Callback has fired: [" + start.format('MMMM D, YYYY') + " to " + end.format('MMMM D, YYYY') + ", label = " + label + "]");
        }

        var optionSet1 = {
            startDate: moment().subtract(29, 'days'),
            endDate: moment(),
            minDate: '01/01/2012',
            maxDate: '12/31/2015',
            dateLimit: {
                days: 60
            },
            showDropdowns: true,
            showWeekNumbers: true,
            timePicker: false,
            timePickerIncrement: 1,
            timePicker12Hour: true,
            ranges: {
                '今天': [moment(), moment()],
                '昨天': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                '过去7天': [moment().subtract(6, 'days'), moment()],
                '过去30天': [moment().subtract(29, 'days'), moment()],
                '本月': [moment().startOf('month'), moment().endOf('month')],
                '上月': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            opens: 'right',
            buttonClasses: ['btn btn-default'],
            applyClass: 'btn-small btn-primary',
            cancelClass: 'btn-small',
            format: 'MM/DD/YYYY',
            separator: ' to ',
            locale: {
                applyLabel: 'Submit',
                cancelLabel: 'Clear',
                fromLabel: 'From',
                toLabel: 'To',
                customRangeLabel: '常规',
                daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                firstDay: 1
            }
        };

        $('#reportrange_right span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));

        $('#reportrange_right').daterangepicker(optionSet1, cb);

        $('#reportrange_right').on('show.daterangepicker', function () {
            console.log("show event fired");
        });
        $('#reportrange_right').on('hide.daterangepicker', function () {
            console.log("hide event fired");
        });
        $('#reportrange_right').on('apply.daterangepicker', function (ev, picker) {
            console.log("apply event fired, start/end dates are " + picker.startDate.format('MMMM D, YYYY') + " to " + picker.endDate.format('MMMM D, YYYY'));
        });
        $('#reportrange_right').on('cancel.daterangepicker', function (ev, picker) {
            console.log("cancel event fired");
        });

        $('#options1').click(function () {
            $('#reportrange_right').data('daterangepicker').setOptions(optionSet1, cb);
        });

        $('#options2').click(function () {
            $('#reportrange_right').data('daterangepicker').setOptions(optionSet2, cb);
        });

        $('#destroy').click(function () {
            $('#reportrange_right').data('daterangepicker').remove();
        });

    });
</script>
<!-- datepicker -->
<script type="text/javascript">
    $(document).ready(function () {

        var cb = function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
            $('#reportrange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
            //alert("Callback has fired: [" + start.format('MMMM D, YYYY') + " to " + end.format('MMMM D, YYYY') + ", label = " + label + "]");
        }

        var optionSet1 = {
            startDate: moment().subtract(29, 'days'),
            endDate: moment(),
            minDate: '01/01/2012',
            maxDate: '12/31/2015',
            dateLimit: {
                days: 60
            },
            showDropdowns: true,
            showWeekNumbers: true,
            timePicker: false,
            timePickerIncrement: 1,
            timePicker12Hour: true,
            ranges: {
                '今天': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            opens: 'left',
            buttonClasses: ['btn btn-default'],
            applyClass: 'btn-small btn-primary',
            cancelClass: 'btn-small',
            format: 'MM/DD/YYYY',
            separator: ' to ',
            locale: {
                applyLabel: 'Submit',
                cancelLabel: 'Clear',
                fromLabel: 'From',
                toLabel: 'To',
                customRangeLabel: 'Custom',
                daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                firstDay: 1
            }
        };
        $('#reportrange span').html(moment().subtract(29, 'days').format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
        $('#reportrange').daterangepicker(optionSet1, cb);
        $('#reportrange').on('show.daterangepicker', function () {
            console.log("show event fired");
        });
        $('#reportrange').on('hide.daterangepicker', function () {
            console.log("hide event fired");
        });
        $('#reportrange').on('apply.daterangepicker', function (ev, picker) {
            console.log("apply event fired, start/end dates are " + picker.startDate.format('MMMM D, YYYY') + " to " + picker.endDate.format('MMMM D, YYYY'));
        });
        $('#reportrange').on('cancel.daterangepicker', function (ev, picker) {
            console.log("cancel event fired");
        });
        $('#options1').click(function () {
            $('#reportrange').data('daterangepicker').setOptions(optionSet1, cb);
        });
        $('#options2').click(function () {
            $('#reportrange').data('daterangepicker').setOptions(optionSet2, cb);
        });
        $('#destroy').click(function () {
            $('#reportrange').data('daterangepicker').remove();
        });
    });
</script>
<!-- /datepicker -->
<script type="text/javascript">
    $(document).ready(function () {
        $('#single_cal1').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_1"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
        $('#single_cal2').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_2"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
        $('#single_cal3').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_3"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
        $('#single_cal4').daterangepicker({
            singleDatePicker: true,
            calender_style: "picker_4"
        }, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#reservation').daterangepicker(null, function (start, end, label) {
            console.log(start.toISOString(), end.toISOString(), label);
            /*alert(start);*/
        });
    });
</script>
<!-- /datepicker -->
<{/block}>