<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title></title>
<script src="./js/zepto.js"></script></head>
<style type="text/css">
    * {
        margin: 0;
        padding: 0;
    }
    .bg {
        position: relative;
    }
    .bg-img {
        width: 100%;
    }
    .number{
        font-family: 'Microsoft YaHei';
    } 
    .time  {
        position: absolute;
        top: 8.1%;
        font-size: 4vw;
        color: #FF8500;             
    }
    .day {
        left: 31.4%;
    }
    .hour {
        left: 46%;
    }
    .minute {
        left: 59.7%;
    }
    .amount {
        position: absolute;
        top: 45%;
        left: 35.2%;
        height: 3.4vh;
        width: 19vw;
        text-align: center; 
        font-size: 5.4vw;
        color: #ffea00;
    }
    //动画背景切换
    @keyframes animatedBackground { from { background-image: url(img/holiday/button-up.png); } to { background-image: url(img/holiday/button-down.png); } }
    .button {
        position: absolute;
        top: 44%;
        left: 64%;
        width: 32vw;
        height: 13vh;
        background-image: url(img/holiday/button-up.png);
        background-repeat: no-repeat;
        background-size: 100% auto;
        animation: animatedBackground 0.3s ease-in-out infinite;
    }
    .process {
        display: none;
        position: absolute;
        background-repeat: no-repeat;
        background-size: 100% auto;
    }
    #pro-1 {
        top: 67.8%;
        left: 61.2%;
        height: 8vh;
        width: 18vw;
        background-image: url(img/holiday/1.png);
    }
    #pro-2 {
        top: 69.5%;
        left: 29.3%;
        height: 8vh;
        width: 32.2vw;
        background-image: url(img/holiday/2.png); 
    }
    #pro-3 {
        top: 73.7%;
        left: 15%;
        height: 20vh;
        width: 27vw;
        background-image: url(img/holiday/3.png);
    }
    #pro-4 {
        top: 86%;
        left: 33%;
        height: 15.6vh;
        width: 64vw;
        background-image: url(img/holiday/4.png);
    }
</style>
<body>
<div class="bg">
    <img src="img/holiday/bg1.png" class="bg-img"/>
        <div class="time day number"></div>
        <div class="time hour number"></div>
        <div class="time minute number"></div>

    <div class="amount number"><{$bCount}></div>
    <div class="button"></div>
    
        <div id="pro-1" class="process"></div>
        <div id="pro-2" class="process"></div>
        <div id="pro-3" class="process"></div>
        <div id="pro-4"class="process"></div>
    
</div>
<script type="text/javascript">
    function setLeftTime($day,$hour,$minute) {
        return function(){
            var date1 = new Date(),
                date2 = new Date('2016/2/16');
            var date3=date2.getTime()-date1.getTime();  //时间差的毫秒数
            //计算出相差天数
            var days=Math.floor(date3/(24*3600*1000))
            //计算出小时数
            var leave1=date3%(24*3600*1000)    //计算天数后剩余的毫秒数
            var hours=Math.floor(leave1/(3600*1000))
            //计算相差分钟数
            var leave2=leave1%(3600*1000)        //计算小时数后剩余的毫秒数
            var minutes=Math.floor(leave2/(60*1000))

            $day.html(days);
            $hour.html(hours);
            $minute.html(minutes);
        }
            
    }
    $(document).ready(function() {
        var $day = $(".day"),
            $hour = $(".hour"),
            $minute = $(".minute");


        setTime = setLeftTime($day,$hour,$minute);
        setTime();
        setInterval("setTime()",60000);
    
        //点击按钮打开页面
        $('.button').on('tap',function(){
            window.open("rule");
        });

        //显示当前进度
        var cur = <{$cCount|default:0}>;
        for(i=1;i<=cur;i++){
            $('#pro-'+i).show();
        }
        


    })
</script>
</body>
</html>
