<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title></title>
    <link rel="stylesheet" href="public/share/a.css" />
    <!--<script type="text/javascript" src="http://api.youziku.com/webfont/FastJS/yzk_005AAB05F1EAE564"></script>-->
</head>
<body>
<div>
    <!--logo-->
    <div class="logo-wrap">
        <img src="public/share/img/logo.png" class="img-logo" />
    </div>

    <!--云彩&内容-->
    <div class="cloud">
        <!--中间文字-->
        <div class="text">
            <span>来<mark>UDO微课堂</mark>刷题<br />经验多&nbsp;&nbsp;升级快</span>
            <p class="content">
                我在UDO微课堂<br />
                <mark><{$sectionName}></mark>的测验中<br />
                击败了<mark><{$defeatRate}></mark>的学生<br />
                排名第<mark><{$rank}></mark>名<br />
                获得<mark><{$title}></mark>的称号<br />
                求超越
            </p>
        </div>
        <!--下部图标-->
        <div class="icon-wrap">
            <img src="public/share/img/black-phone.png" class="phone" />
            <img src="public/share/img/people.png" class="icon icon-left"/>


            <img src="public/share/img/icon.png" class="icon icon-right"/>
            <span class="name"><{$title}></span>
            <div style="clear: both;"></div>
        </div>
        <!--下部按钮-->
        <a class="btn" href="http://www.howdo.cc/download/dl_stu.html"></a>


    </div>

</div>
<!--<script type="text/javascript">
   $youziku.load(".text", "ce3efbd73ab1445d94932815a3bb5aee", "minijiankatong");
   $youziku.draw();
</script>-->
</body>
</html>
