<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title></title>
    <style type="text/css">
    * {
        margin: 0;
        padding: 0;
    }
    .bg {
        position: relative;
    }
    .bg-img {
        width: 100%;
    }
    </style>
    <body>
    	<div class="bg">
    		<img src="img/holiday/rule.png" class="bg-img"/>
    	</div>

    </body>
</html>