<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title></title>
    <link rel="stylesheet" href="public/share/b.css" />
    <!--<script type="text/javascript" src="http://api.youziku.com/webfont/FastJS/yzk_005AAB05F1EAE564"></script>-->
</head>
<body>
<div>
    <!--logo-->
    <div class="logo-wrap">
        <img src="public/share/img/logo.png" class="img-logo" />
    </div>
    <!--云彩&内容-->
    <div class="cloud">
        <!--中间文字-->
        <div class="text">
            <span>无聊刷手机不如来<br /><mark>UDO微课堂看微课</mark></span>
            <p class="content">
                我在这里看了<br />
                <mark style="font-family:宋体"><{$name}></mark>推出的<br />
                <mark style="font-family:宋体"><{$title}></mark>微课<br />
                居然全听懂了<br />
                开森继续努力<br />
            </p>
        </div>
        <!--下部图标-->
        <div class="icon-wrap">
            <img src="public/share/img/black-phone.png" class="phone" />
            <img src="public/share/img/people.png" class="icon icon-left"/>

            <div class="text board">
                <div class="course" style="background-image:url(<{$logo}>)"></div>
            </div>
            <div style="clear: both;"></div>
        </div>
        <!--下部按钮-->
        <a class="btn" href="http://www.howdo.cc/download/dl_stu.html"></a>


    </div>
</div>
<!--<script type="text/javascript">
      $youziku.load(".text", "ce3efbd73ab1445d94932815a3bb5aee", "minijiankatong");
    /*$youziku.load("#id2", "ce3efbd73ab1445d94932815a3bb5aee", "minijiankatong");*/
    /*$youziku.load(".class1", "ce3efbd73ab1445d94932815a3bb5aee", "minijiankatong");*/
    /*$youziku.load(".class2", "ce3efbd73ab1445d94932815a3bb5aee", "minijiankatong");*/
    /*．．．*/
       $youziku.draw();
</script>-->

</body>
</html>