<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>版权声明</title>
<link rel="stylesheet" href="public/base/css/howdo-framework.css"/>
<link rel="stylesheet" href="public/base/css/font-awesome.min.css"/>
<link rel="stylesheet" href="public/base/css/common.css"/>
<style>
.text-box{font-size: 14px;color: #333;  padding: 0 10px;  line-height: 1.6em;}
.text-box p{ text-indent: 2em;}
</style>
</head>
<body>
<div class="wrapper text-box">
	 <h3 class="text-center">版权声明</h3>
	 <p>好度科技在本服务中提供的题目答案、解析和扩展性内容（包括但不限于文本、图片、音频、视频、图表等）的知识产权均归属好度科技所有。除另有特别声明外，好度科技提供本服务时所依托软件的著作权、专利权及其他知识产权均归属好度科技所有。</p>
	 <p>上述及其他任何好度科技依法拥有的知识产权均受到法律保护，未经好度科技书面许可，任何个人或单位不得以任何形式进行翻版、复制、转载、篡改或以其他方式使用或创造衍生作品。</p>
</div>
</body>
</html>