<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>广告推广</title>
    <link rel="stylesheet" href="public/base/css/howdo-framework.css"/>
    <link rel="stylesheet" href="public/base/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="public/base/css/common.css"/>
    <style>
        .mob-about-top{ padding:30px 0 0px; overflow:hidden;}
        .mob-about{margin-top:30px;}
        a.about-blue{ color:#1abc9c; font-weight:normal;}
        .about-footer{text-align:center; line-height:2em; margin-top:50px;}
    </style>
</head>
<body>
This is an ad.
</body>
</html>