<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>如何在UDO学生端用学分兑换课程</title>
<link rel="stylesheet" href="public/base/css/howdo-framework.css"/>
<link rel="stylesheet" href="public/base/css/font-awesome.min.css"/>
<link rel="stylesheet" href="public/base/css/common.css"/>
<style>
.text-box{ font-size: 14px;color: #333; padding: 0 10px; line-height: 1.6em;}
.text-box p,.text-box dd{ text-indent: 2em;}
.text-box dt{ margin:10px 0 5px;}
.text-box dd p{  margin-bottom: 0;}
.gd-img {
        width: 90%;
        text-align:center;
        position:relative; 
        left:5%; 
    }
    body{
      margin:0 auto ;
    }
</style>
</head>
<body>
<div class="wrapper text-box">
     <h3 class="text-center">如何在UDO学生端用学分兑换课程</h3>
     <dl>
        <dt>1. 如何用学分兑换课程</dt>
        <dd>
          <p> (1) 进入登陆页，打开想要观看的课程，标记即为需要学分兑换后才可以观看的课程。</p>
          <br>
          <img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F8.png" class="gd-img"/>
          <br>
          <p> (2) 选择课程后，提示是否使用学分兑换此课程，点【确定】兑换成功。</p>
          <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F9.png" class="gd-img"/><br>
          <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F10.png" class="gd-img"/><br>
          <p>兑换成功后显示【已兑换】</p>
          <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F11.png" class="gd-img"/><br>
          </dd>
        <dt>2. 怎么查询剩余多少学分</dt>
        <dd>
            <p>在功能页面选中"学分"，可以查看学分情况</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F12.png" class="gd-img"/><br>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F13.png" class="gd-img"/><br>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F14.png" class="gd-img"/><br>
        </dd>
        <dt>3. 怎么能获得学分</dt>
        <dd>
            <p>学分可以通过以下几种方式获得</p>
            <p>方法一：春节期间同学们可以观看视频，查看题目解析，对视频点赞，发布评论，分享，在任务中看微课，做作业。下表是每日对应操作次数与获得数值数。</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F15.png" class="gd-img"/><br>
            <p>方法二： U币兑换学分，在功能列表页面点 “学分”—>“去兑换” ，选择相应的学分【确认兑换】</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F16.png" class="gd-img"/><br>
            <p>如果出现U币余额不足情况，点【确定】去充值，如果余额充足，直接兑换成功，学分数量增加。</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F17.png" class="gd-img"/><br>
        </dd>
     </dl>
</div>
</body>
</html>