<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>如何在UDO学生端用U币购买课程</title>
<link rel="stylesheet" href="public/base/css/howdo-framework.css"/>
<link rel="stylesheet" href="public/base/css/font-awesome.min.css"/>
<link rel="stylesheet" href="public/base/css/common.css"/>
<style>
.text-box{ font-size: 14px;color: #333; padding: 0 10px; line-height: 1.6em;}
.text-box p,.text-box dd{ text-indent: 2em;}
.text-box dt{ margin:10px 0 5px;}
.text-box dd p{  margin-bottom: 0;}
.gd-img {
        width: 90%;
        text-align:center;
        position:relative; 
        left:5%; 
    }
    body{
      margin:0 auto ;
    }
</style>
</head>
<body>
<div class="wrapper text-box">
     <h3 class="text-center">如何在UDO学生端用U币购买课程</h3>
     <dl>
        <dt>Step1:</dt>
        <dd>
          <p>进入到UDO微课堂以后，选择想要观看的频道，可以直接点击“购买课程”，也可以选择想要观看的某个课程点击进去。</p>
          <br>
          <img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F1.png" class="gd-img"/>
          <br>
          </dd>
        <dt>Step2:</dt>
        <dd>
            <p>进入到付费课程之后，点击“购买”。</p>
            
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F2.png" class="gd-img"/><br>
            
        </dd>
        <dt>Step3:</dt>
        <dd>
            <p>如果我们的账户内有足够的U币时，可以直接购买该课程；当U币余额不足时，我们需要通过支付宝去充值U币。</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F3.png" class="gd-img"/><br>
        </dd>
        <dt>Step4:</dt>
        <dd>
            <p>进入到U币充值界面之后，我们可以选择需要充值的金额，然后进入支付宝，确认支付即可。</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F4.png" class="gd-img"/><br>
            <p>（如果在支付宝 没有登录的情况下，我们只需要通过手机号登录，输入手机接收到的验证码即可。</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F5.png" class="gd-img"/><br>
            <p>如果该支付宝账号没有绑定银行卡的话，也是无法进行支付的，以下是支付宝绑定银行卡的操作步骤。</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F6.png" class="gd-img"/><br>
            <p>注：同学们也可以直接从左侧列表中预先进行U币充值，这样就可以直接观看付费课程了。</p>
            <br><img src= "http://7xphlf.com2.z0.glb.qiniucdn.com/udoguide%2F7.png" class="gd-img"/><br>
        </dd>
     </dl>
</div>
</body>
</html>