<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>下载app</title>
	    <link rel="stylesheet" href="public/base/css/howdo-framework.css">
	    <style>
	    a{padding: 10px 0}
	    </style>
</head>
<body>
<div class="wrapper">
<div class="row" style="padding:20px">
		<br>
<a class="btn btn-success btn-lg btn-block" href="<{$url.apk}>">下载安卓版</a>
<br><br>
<a  class="btn btn-success btn-lg  btn-block" href="<{$url.appstore}>">下载ISO版</a>
<br>

</div>

	
</div>

	
</body>
</html>